### ISSUE TITLE
I:[0.5] Establecer lineamientos iniciales  de  configuración para el Readme.md

### ISSUE THREAD

**Issue by Ivan-dela-cruz** [Ivan-dela-cruz/challengue-laravel#1]
**Description**
Establecer lineamientos de  configuración para Readme.md

**Acceptance Test**
- [x]  Descripción del proyecto
- [x]  Requerimientos
- [x]  Herramientas de desarrollo
- [x]  Configuración deploy entorno DEV
- [x]  Ambientes establecido

**Implementation Notes**
none

**Subtasks**
N/A

**Planning Estimate**
0.5
